### ISSUE TITLE
PMDM_config.h 

### ISSUE THREAD

**Issue by RAWJUNGLE** [ScharreSoft/The-Poor-Mans-Drum-Machine#1]
Hi. Do you have the ability to implement these features in the config file? 
1. Add the ability to disable 74HC595 and TLC594NT to make it easier to build and remove unnecessary components. 
2. Add the ability to disable Accent. 

Thank you.

**Comment by ScharreSoft** [comment]
I am not sure if I understand what your goal is. 

1 you want to use less voices, so only one 74HC595?
2 you don't want to use accent at all, so only drum voices with only a trigger input?

**Comment by RAWJUNGLE** [comment]
1. Yes
2. Yes

**Comment by RAWJUNGLE** [comment]
I want to be able to - not connect these chips in the circuit(schematic)

**Comment by ScharreSoft** [comment]
But in the end you would connect at least one 74hc595 and one TLC5940 I assume?

**Comment by RAWJUNGLE** [comment]
Yes

**Comment by RAWJUNGLE** [comment]
1. - 8 instruments (triggers), without accent. 
2. - possibility of not connecting inside the circuit, two ic's TLC5940 and 74hc595. (one TLC5940 and 74HC595).

**Comment by ScharreSoft** [comment]
About using the circuit without accent: 

I assume that you will use at least one TLC5940, because you want to see the LEDs going on and off when you push buttons, right?
If so, you can leave out U6 and all the opamp buffers and associated components. The Arduino pin that was connected to pin 26 of U6 should now be connected to pin 26 of U7. 

Next, there should be a firmware update to test it. The problem is that I will not be able to test it, you will have to test it your self.

Have you started building yet? Do you have components?

**Comment by RAWJUNGLE** [comment]
I want to make it easier to assemble first. 
I don't have the components yet. 
You can check it yourself. All you have to do is take the chips out of your board. 


I need the buttons to be illuminated and everything to work without accent. 
If I do it the way I want, the code won't work because the arduino won't detect the 2 ic's
![Снимок экрана 2023-04-19 в 11 53 20](https://user-images.githubusercontent.com/108550345/233023308-f2aa460d-495c-4405-9b21-fe2d7704ac03.png)

**Comment by ScharreSoft** [comment]
I removed U9 and it works fine. 
I removed U6 from the circuit and connected Arduino pin D11 to pin 26 from U7. 
Made some quick changes to the firmware, it does not work flawless yet as expected. Needs more changes but it should be possible. In the end I am not sure if it would be easier to make a different firmware (PMDM-Light) instead of an option in the config file. 

More testing to be done...

**Comment by RAWJUNGLE** [comment]
I think that the code should be made modular, so that it is possible to disable certain IC's. 
So that any user could configure the sequencer to suit himself and not distract you unnecessarily.

**Comment by ScharreSoft** [comment]
Yes, that would be best and I will try to do that. But I am not sure how many bugs I will encounter and if they are solved easily.

**Comment by ScharreSoft** [comment]
Seems like it wasn't that difficult after all. But it still needs some more testing with the different configurations. There is now a variable "USE_ACCENT" in the config file. When set to 0, U6 can (must) be omitted and Arduino pin D11 must be connected to pin 26 from U7. 

U9 can be left out without a problem. No changes needed in the firmware, just set MaxVoices to 8.

So it is not really a matter of 'disabling ICs' in the config file. Just leave them out and set USE_ACCENT to 0.

**Comment by RAWJUNGLE** [comment]
I just want not to make 4 ic's on PCB, but I want to get by with 2 ic's

**Comment by RAWJUNGLE** [comment]
and you haven't updated the code yet.

**Comment by ScharreSoft** [comment]
Yes I understand. You can make the circuit as it is in your drawing with one TLC and one 74hc595. I'll update the code after I have tested it thoroughly.

**Comment by RAWJUNGLE** [comment]
Thank you, please let me know how to check.

**Comment by ScharreSoft** [comment]
What do you mean 'how to check' ?

I have uploaded the new firmware (v4.1.1). There are two new parameters in the config file:

USE_ACCENT
LED_Index

I will update the build guide later, but for now: Arduino pin D11 must be connected to pin 26 from U7 if using only one TLC.

**Comment by RAWJUNGLE** [comment]
thanks!
